"""Added Role model with RoleType as Enum

Revision ID: 0e1c212cfdad
Revises: bcaa3ef6702f
Create Date: 2026-08-21 20:28:14.673872

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "0e1c212cfdad"
down_revision: Union[str, Sequence[str], None] = "bcaa3ef6702f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


role_enum = postgresql.ENUM("user", "admin", "moderator", name="roletype", create_type=False)


def upgrade() -> None:
    """Upgrade schema."""

    role_enum.create(op.get_bind(), checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "roles",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("title", sa.String(length=50), nullable=False),
        sa.Column("code", role_enum, nullable=False),
        sa.Column("description", sa.String(length=250), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_roles")),
        sa.UniqueConstraint("code", name=op.f("uq_roles_code")),
    )
    op.add_column("users", sa.Column("role_id", sa.Integer(), nullable=True))  # 'nullable' property need to update to True
    op.create_foreign_key(op.f("fk_users_role_id_roles"), "users", "roles", ["role_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_users_role_id_roles"), "users", type_="foreignkey")
    op.drop_column("users", "role_id")
    op.drop_table("roles")

    role_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
